import React from "react";
import Head from "next/head";
import { useTimerContext } from "@context/timerContext";

const Header = () => {
  const { display } = useTimerContext();
  return (
    <Head>
      <title>{display ?? "Pomodoro"}</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/images/clipboard-notes.svg" />
    </Head>
  );
};

export default Header;
