import React from "react";
import Head from "next/head";

const Header = () => {
  return (
    <Head>
      <title>Pomodoro</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/images/clipboard-notes.svg" />
    </Head>
  );
};

export default Header;
